ProjetDjango/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('App1/', include('djangoApp.urls') )
]

djangoApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from .views import MatiereCreateView, MatiereUpdateView, MatiereDeleteView, MatiereListView,DevoirDownloadView,DevoirListView
from .views import FiliereCreateView, FiliereUpdateView, FiliereDeleteView, FiliereListView,CourListViewEtudiant,ProjetListViewEtuduant
from .views import CourCreateView, CourUpdateView, CourDeleteView, CourListView, CourDeleteView,CourDownloadView,CourShowView
from .views import ProjetCreateView, ProjetUpdateView, ProjetListView, ProjetDeleteView,ProjetDownloadView,ProjetShowView
from djangoApp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', views.registerFunction, name="register"),
    # path('inscription/', views.register, name='inscription'),
    path('login/', views.loginFunction, name='login'),
    path('adminpage/', views.admin, name='adminpage'),
    path('etudiant/', views.etudiantPage, name='etudiantPage'),
    path('enseignantMatiere/', views.listeMatiereEnseignant, name='enseignantMatiere'),
    path('enseignant/', views.enseignant, name='enseignant'),
    path('liste/', views.liste_matiere ,name='liste_des_matiere'),
    path('register/enseignant', views.registerEnseignantFunction, name="registerEnseignant"),
    path('register/etudiant', views.registerEtudiantFunction, name="registerEtudiant"),
    path('', views.registerAdminFunction, name="registerAdmin"),
    path('liste_enseignants/', views.liste_enseignants, name='liste_enseignants'),
    # Matiere URL

    path('matiere/create/', MatiereCreateView.as_view(), name='matiere-create'),
    path('matiere/<int:pk>/update/', MatiereUpdateView.as_view(), name='matiere-update'),
    path('matiere/<int:pk>/delete/', MatiereDeleteView.as_view(), name='matiere-delete'),
    path('matiere/', MatiereListView.as_view(), name='matiere-list'),
     # Filiere URL
    path('filiere/create/', FiliereCreateView.as_view(), name='filiere-create'),
    path('filiere/<int:pk>/update/', FiliereUpdateView.as_view(), name='filiere-update'),
    path('filiere/<int:pk>/delete/', FiliereDeleteView.as_view(), name='filiere-delete'),
    path('filiere/', FiliereListView.as_view(), name='filiere-list'),
    # Projet URL
    path('projet/create/', ProjetCreateView.as_view(), name='projet-create'),
    path('projet/<int:pk>/update/', ProjetUpdateView.as_view(), name='projet-update'),
    path('projet/list/', ProjetListView.as_view(), name='projet-list'),
    path('projet/<int:pk>/delete/', ProjetDeleteView.as_view(), name='projet-delete'),
    path('projet/<int:pk>/download/', ProjetDownloadView.as_view(), name='projet-download'),
    path('devoir/<int:pk>/download/', DevoirDownloadView.as_view(), name='devoir-download'),
    path('projet/soumission/',  DevoirListView.as_view(), name='projet-soumission'),
    path('projet/<int:pk>/show/', ProjetShowView, name='projet-show'),
    # Cour URL
    path('cour/create/', CourCreateView.as_view(), name='cour-create'),
    path('cour/<int:pk>/update/', CourUpdateView.as_view(), name='cour-update'),
    path('cour/list/', CourListView.as_view(), name='cour-list'),
    path('cour/<int:pk>/delete/', CourDeleteView.as_view(), name='cour-delete'),
    path('cour/<int:pk>/download/', CourDownloadView.as_view(), name='cour-download'),
    path('cour/<int:pk>/show/', CourShowView, name='cour-show'),
  
    # Etudiant
    path('cour_list_etudiant', CourListViewEtudiant.as_view(), name='cour_list_etudiant'),
    path('projet_list_etudiant', ProjetListViewEtuduant.as_view(), name='projet_list_etudiant'),



    path('testAdmin/', views.testAdmin, name='testAdmin'),
    path('testEnseignant/', views.testEnseignant, name='testEnseignant'),

    path('AdminAcceuil/', views.AdminAcceuil, name='AdminAcceuil'),
    path('EnseignantAcceuil/', views.EnseignantAcceuil, name='EnseignantAcceuil'),
    path('EtudiantAcceuil/', views.EtudiantAcceuil, name='EtudiantAcceuil'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MaxValueValidator 
import datetime

def validate_file_size(value):
    max_size = 5 * 1024 * 1024  # 5 Mo en octets
    if value.size > max_size:
        raise ValidationError('La taille du fichier ne peut pas dépasser 5 Mo.')



# Create your models here.


# class Etudiant(models.Model):
#     user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
#     nomEtudiant=models.CharField(max_length=3000,null=True)
#     cours=models.CharField(max_length=3000)
#     instructeur=models.CharField(max_length=3000)
#     filiere=models.CharField(max_length=3000)
#     anneeAcademique=models.CharField(max_length=3000)

# class Enseignant(models.Model):
#     user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
#     cours=models.CharField(max_length=3000)


class Matiere(models.Model):
    nomMatiere=models.CharField(max_length=3000)
    
    def __str__(self):
     return self.nomMatiere

class Filiere(models.Model):
    nomFiliere=models.CharField(max_length=3000)
    matieres = models.ManyToManyField(Matiere)

    def __str__(self):
     return self.nomFiliere


class User(AbstractUser):
    numero=models.PositiveIntegerField(null=True)
    is_etudiant = models.BooleanField(null=True)
    is_enseignat = models.BooleanField(null=True)
    is_administrateur = models.BooleanField(null=True)
    filire_etudiant = models.ForeignKey(Filiere, null=True, on_delete=models.SET_NULL)
    matiere_enseignant = models.ManyToManyField(Matiere)

    def __str__(self):
     return self.username


class Projet(models.Model):
    # etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE, null=True,)
    etudiant = models.ForeignKey(User, on_delete=models.CASCADE, null=True,)
    matiere=models.ForeignKey(Matiere,on_delete=models.CASCADE,)
    intituleProjet=models.CharField(max_length=3000)
    fichierProjet=models.FileField(upload_to='devoirs/', validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), validate_file_size])
    description=models.TextField()
    date_creation = models.DateField(default=datetime.date.today)
    deadline = models.DateField(null=True)
    devoir_soumis=models.FileField(upload_to='devoirs_soumis/',  null=True, validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), validate_file_size])

    def __str__(self):
        return self.intituleProjet, self.matiere, self.fichierProjet,self.description,self.date_creation,self.deadline

class Cour(models.Model):
    # etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE, null=True,)
    # etudiant = models.ForeignKey(User, on_delete=models.CASCADE, null=True,)
    matiere=models.ForeignKey(Matiere,on_delete=models.CASCADE,)
    intituleCour=models.CharField(max_length=3000)
    fichierCour=models.FileField(upload_to='devoirs/', validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), validate_file_size])
    description=models.TextField()
    date_creation = models.DateField(default=datetime.date.today)
   

    def __str__(self):
        return self.intituleCour, self.matiere, self.fichierCour,self.description,self.date_creation



class Devoir(models.Model):
    etudiant = models.ForeignKey(User, on_delete=models.CASCADE, null=True,)
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE,)
    date_soumission = models.DateTimeField(default=datetime.date.today)
    fichier_soumis = models.FileField(upload_to='devoirs_soumis/', validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), validate_file_size])
    commentaires = models.TextField()
    def __str__(self):
        return f"{self.etudiant} - {self.projet}"


class Projettest(models.Model):
    etudiant = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    intituleProjet = models.CharField(max_length=3000)
    fichierProjet = models.FileField(upload_to='devoirs/', validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), validate_file_size])
    description = models.TextField()
    date_creation = models.DateField(default=datetime.date.today)
    deadline = models.DateField(null=True)
    devoir_soumis = models.FileField(upload_to='devoirs_soumis/', null=True, validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), validate_file_size])

    def __str__(self):
        return self.intituleProjet


class Matieretest(models.Model):
    nomMatiere = models.CharField(max_length=3000)
    projets = models.ManyToManyField(Projettest) 

djangoApp/forms.py
from django import forms
from django.contrib.auth import login
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from .models import User, Filiere, Matiere,Projet,Devoir,Cour


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "forms-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',
                  'is_administrateur', 'is_etudiant', 'is_enseignat','numero','filire_etudiant','matiere_enseignant')
        
class MatieresCheckboxSelect(forms.CheckboxSelectMultiple):
    def label_from_instance(self, matiere):
        return matiere.nomMatiere

class FiliereForm(forms.ModelForm):
    matieres = forms.ModelMultipleChoiceField(
        queryset=Matiere.objects.all(),
        widget=MatieresCheckboxSelect,
        label="Matieres associées"
    )
    class Meta:
        model = Filiere
        fields = ['nomFiliere', 'matieres']

class ProjetForm(forms.ModelForm):
    class Meta:
        model=Projet
        fields=['matiere', 'intituleProjet', 'fichierProjet', 'description','deadline']

class CourForm(forms.ModelForm):
    class Meta:
        model=Cour
        fields=['matiere', 'intituleCour', 'fichierCour', 'description']

class DevoirForm(forms.ModelForm):
    class Meta:
        model = Devoir
        fields = ['fichier_soumis', 'commentaires']


class ProjettestForm(forms.ModelForm):
    class Meta:
        model=Projet
        fields=['intituleProjet', 'fichierProjet', 'description','deadline']


class SignUpFormEnseignant(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    # matiere_enseignant = forms.ModelMultipleChoiceField(
    #     queryset=Matiere.objects.all(),
    #     widget=MatieresCheckboxSelect,
    #     required=False  # Si vous voulez que ce champ ne soit pas obligatoire
    # )

    # matiere_enseignant = forms.ModelMultipleChoiceField(
    #     queryset=Matiere.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    #     label="Matieres associées"
    # )
    

    is_enseignat = forms.BooleanField(initial=True, required=True, widget=forms.HiddenInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',
            'is_enseignat','numero','matiere_enseignant')


class SignUpFormEtudiant(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    is_etudiant = forms.BooleanField(initial=True, required=True, widget=forms.HiddenInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',
            'is_etudiant','numero','filire_etudiant')
        

class SignUpFormAdimin(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    is_administrateur = forms.BooleanField(initial=True, required=True, widget=forms.HiddenInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',
            'is_administrateur','numero',)

djangoApp/templates/djangoApp/Ajout.html
{% extends 'djangoApp/base.html'%}
{% block content %}


{% endblock content%}

djangoApp/templates/djangoApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moodle 2.0</title>
    <link rel="stylesheet" type="text/css" href="{% static 'djangoApp/css/bootstrap.css' %}">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger"> Formulaire d'inscription </h2>
        {% block content%} {% endblock content %}
    </div>
    <script src="{% static 'djangoApp/js/jquery.js' %}"></script>
    <script src="{% static 'djangoApp/js/bootstrap.js' %}"></script>
    <script src="{% static 'djangoApp/js/popper.js' %}"></script>
</body>
</html>

djangoApp/templates/djangoApp/cour_liste_etudiant.html
{% extends 'template.html' %}



{% block main_content %}
    <section class="event_section layout_padding">
        
        <div class="container">
        <div class="heading_container">
            <h3>
            </h3>
            <p>
 
            </p>
        </div>
        {% for cour in cour_list %}
        <div class="event_container">
            <div class="box">
                {{ cour.intituleCour }}
                
            </div>
        </div>
        {% endfor %}
        <div class="btn-box">
            <a href="{% url 'cour-create' %}">Ajouter </a>
            </a>
        </div>
        </div>
    
    </section>
{% endblock  %}

djangoApp/templates/djangoApp/dashBordEnseignant.html
<!DOCTYPE html>
<html>
<head>
    <!-- ... autres balises d'en-tête ... -->
</head>
<body>
    <h1>Liste des Matières</h1>
    <ul>
        {% for matiere in liste_matiere %}
            <li>{{ matiere.nomMatiere }}</li>
        {% endfor %}
    </ul>
</body>
</html>

djangoApp/templates/djangoApp/dashBordEtudiant.html
{% extends 'template.html' %}



{% block main_content %}
{% for matiere in liste_matiere %}
            <li>{{ matiere.nomMatiere }}</li>
        {% endfor %}
{% endblock  %}

djangoApp/templates/djangoApp/index.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Joson</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="css/responsive.css" rel="stylesheet" />
</head>

<body>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <h3>
              Joson
            </h3>
            <span> college</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <ul class="navbar-nav  ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html"> About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="course.html"> Courses </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="event.html"> Events </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="login.html">Login</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
              <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
            </form>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class=" slider_section position-relative">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container">
              <div class="row">
                <div class="col">
                  <div class="detail-box">
                    <div>
                      <h1>
                        E D U C A T I O N
                      </h1>
                      <a href="">
                        Read More
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container">
              <div class="row">
                <div class="col">
                  <div class="detail-box">
                    <div>
                      <h1>
                        E D U C A T I O N
                      </h1>
                      <a href="">
                        Read More
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container">
              <div class="row">
                <div class="col">
                  <div class="detail-box">
                    <div>
                      <h1>
                        E D U C A T I O N
                      </h1>
                      <a href="">
                        Read More
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end slider section -->
  </div>


  <!-- info section -->
  <section class="info_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_menu">
            <h5>
              QUICK LINKS
            </h5>
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html"> About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="course.html"> Courses </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="event.html"> Events </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="login.html">Login</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_course">
            <h5>
              TOP RATED COURSE
            </h5>
            <p>
              There are many variations of passages of Lorem Ipsum available,
              but the majority have suffered alteration in some form, by
              injected humou
            </p>
          </div>
        </div>

        <div class="col-md-5 offset-md-1">
          <div class="info_news">
            <h5>
              FOR ANY QUERY, PLEASE WRITE TO US
            </h5>
            <div class="info_contact">
              <a href="">
                Location
              </a>
              <a href="">
                demo@gmail.com
              </a>
              <a href="">
                Call : +01 1234567890
              </a>
            </div>
            <form action="">
              <input type="text" placeholder="Enter Your email" />
              <button>
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      &copy; 2021 All Rights Reserved By
      <a href="https://html.design/">Free Html Templates</a>
    </p>
  
  </footer>

   
  <footer class="container-fluid footer_section">
  
      <p>
        Distributed By 
        <a href="https://themewagon.com/">Themewagon</a>
      </p>
  
  </footer>
 
  <!-- footer section -->

  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.js"></script>

</body>

</html>

djangoApp/templates/djangoApp/login.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Etudiant</title>
</head>
<body>
    <h2>Section etudiant </h2>
</body>
</html>

djangoApp/templates/djangoApp/loginPage.html
{% extends 'template.html' %}



{% block main_content %}

<section class="login_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="detail-box">
            <h3>

            </h3>
            <p>
     
            <a href="">
      
            </a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="login_form">
            <h5>
              Login Now
            </h5>
             <form method="POST">
                {% csrf_token %}
                <fieldset>
                  <div class="field">
                    <label class="label_field">Nom utlisateur</label>
                    <input type="text" name="username" placeholder="Username" />
                  </div>
                  <div class="field">
                    <label class="label_field"> mot de passe</label>
                    <input
                      type="password"
                      name="password"
                      placeholder="Password"
                    />
                  </div>
 
                  <div class="field margin_0">
                    <input
                      class="btn login_btn "
                      type="submit"
                      value="connexion"
                    />
                  </div>
                </fieldset>
              </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock  %}

djangoApp/templates/djangoApp/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enseingnat</title>


</head>
<body>
    <h2>Section enseingant</h2>
</body>
</html>

djangoApp/templates/djangoApp/projet_list_etudiant.html
{% extends 'template.html' %}



{% block main_content %}

<section class="event_section layout_padding">
    {% block content %}
      <div class="container">
        <div class="heading_container">
          <h3>
          </h3>
          <p>

          </p>
        </div>
        {% for projet in object_list %}
        <div class="event_container">
          <div class="box">
            <li>
                
            <a href="{% url 'projet-show' projet.pk %}"> {{ projet.intituleProjet }}</a>
              <a href="{% url 'projet-download' projet.pk %}">Télécharger</a>
              <a href="{% url 'projet-show' projet.pk %}"> Soumettre </a>
             
              </li>
          </div>
        </div>
        {% endfor %}
        <div class="btn-box">
            <a href="{% url 'projet-create' %}">Ajouter </a>
          </a>
        </div>
      </div>
    {% endblock %}
  </section>
{% endblock  %}

djangoApp/templates/djangoApp/registerPage.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enregistrement </title>
    <link rel="stylesheet" type="text/css" href="{% static 'djangoApp/css/bootstrap.css' %}">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger"> Formulaire d'enregistrement </h2>
        {% block content%} {% endblock content %}
    </div>
    <form method="POST" action="">
        {% csrf_token %}
        <fieldset>
          <div class="field">
            <label class="label_field">Nom utilisateur</label>
            {{ form.username }}
          </div>
          <div class="field">
            <label class="label_field">Email</label>
            {{ form.email }}
            <div class="field">
              <label class="label_field">password</label>
              {{ form.password1 }}
            </div>
            <div class="field">
              <label class="label_field">password conf</label>
              {{ form.password2 }}
            </div>
          </div>
          <div class="field">
            <label class="label_field">Administrateur</label>
            {{ form.is_administrateur }}
          </div>
          <div class="field">
            <label class="label_field">etudiant</label>
            {{ form.is_etudiant }}
          </div>
          <div class="field">
            <label class="label_field">Enseignant</label>
            {{ form.is_enseignat }}
          </div>
          <div class="field">
            <label class="label_field">Numero</label>
            {{ form.numero }}
          </div>
          <div class="field">
            <a class="forgot" href="{% url 'login' %}"
              >avez-vous un compte?</a
            >
          </div>
          {{ form.errors }}
          <div class="field margin_0">
            <label class="label_field hidden">hidden label</label>
            <button class="main_bt">S'inscrire</button>
          </div>
        </fieldset>
      </form>

      <script src="{% static 'djangoApp/js/jquery.js' %}"></script>
      <script src="{% static 'djangoApp/js/bootstrap.js' %}"></script>
      <script src="{% static 'djangoApp/js/popper.js' %}"></script>
</body>
</html>